from copy import deepcopy
from typing import Any


AUTONETLAB_ML_TRAINING_SAMPLES: list[dict[str, Any]] = [
    {
        "target_topic": "default_gateway",
        "priority": "high",
        "scenario_id": "srl-edge-link",
        "difficulty": "easy",
        "failed_check_ids": ["srl_check_4_client_default_gateway"],
        "failed_topics": ["default_gateway"],
        "affected_topics": ["default_gateway", "connectivity_testing"],
        "fault_resolution_score": 80,
        "network_health_score": 80,
    },
    {
        "target_topic": "connectivity_testing",
        "priority": "medium",
        "scenario_id": "srl-edge-link",
        "difficulty": "easy",
        "failed_check_ids": ["srl_check_5_gateway_connectivity"],
        "failed_topics": ["connectivity_testing"],
        "affected_topics": ["default_gateway", "connectivity_testing"],
        "fault_resolution_score": 80,
        "network_health_score": 80,
    },
    {
        "target_topic": "ip_addressing",
        "priority": "high",
        "scenario_id": "srl-edge-link",
        "difficulty": "medium",
        "failed_check_ids": [
            "srl_check_1_router_gateway_address",
            "srl_check_3_client_address",
        ],
        "failed_topics": ["ip_addressing"],
        "affected_topics": ["ip_addressing", "connectivity_testing"],
        "fault_resolution_score": 60,
        "network_health_score": 60,
    },
    {
        "target_topic": "static_routing",
        "priority": "high",
        "scenario_id": "branch-static-routing",
        "difficulty": "medium",
        "failed_check_ids": [
            "branch_check_5_srl1_route_to_client2",
            "branch_check_6_srl2_route_to_client1",
        ],
        "failed_topics": ["static_routing", "connectivity_testing"],
        "affected_topics": ["static_routing", "connectivity_testing"],
        "fault_resolution_score": 50,
        "network_health_score": 66,
    },
    {
        "target_topic": "default_gateway",
        "priority": "high",
        "scenario_id": "branch-static-routing",
        "difficulty": "easy",
        "failed_check_ids": ["branch_check_2_client1_default_gateway"],
        "failed_topics": ["default_gateway"],
        "affected_topics": ["default_gateway", "connectivity_testing"],
        "fault_resolution_score": 72,
        "network_health_score": 72,
    },
    {
        "target_topic": "connectivity_testing",
        "priority": "medium",
        "scenario_id": "branch-static-routing",
        "difficulty": "medium",
        "failed_check_ids": [
            "branch_check_7_client1_to_client2_connectivity",
            "branch_check_8_client2_to_client1_connectivity",
        ],
        "failed_topics": ["connectivity_testing"],
        "affected_topics": ["connectivity_testing", "static_routing"],
        "fault_resolution_score": 66,
        "network_health_score": 66,
    },
    {
        "target_topic": "static_routing",
        "priority": "high",
        "scenario_id": "campus-core-routing",
        "difficulty": "hard",
        "failed_check_ids": [
            "campus_check_9_srl3_transit_routes",
            "campus_check_10_srl4_transit_routes",
            "campus_check_11_srl2_route_to_client1",
        ],
        "failed_topics": ["static_routing", "connectivity_testing"],
        "affected_topics": ["static_routing", "connectivity_testing"],
        "fault_resolution_score": 45,
        "network_health_score": 63,
    },
    {
        "target_topic": "default_gateway",
        "priority": "high",
        "scenario_id": "campus-core-routing",
        "difficulty": "easy",
        "failed_check_ids": [
            "campus_check_2_client1_default_gateway",
            "campus_check_4_client2_default_gateway",
        ],
        "failed_topics": ["default_gateway"],
        "affected_topics": ["default_gateway", "connectivity_testing"],
        "fault_resolution_score": 72,
        "network_health_score": 72,
    },
    {
        "target_topic": "interface_state",
        "priority": "high",
        "scenario_id": "campus-core-routing",
        "difficulty": "medium",
        "failed_check_ids": [
            "campus_check_7_srl1_edge_and_core_interfaces",
            "campus_check_8_srl2_edge_and_core_interfaces",
        ],
        "failed_topics": ["interface_state", "connectivity_testing"],
        "affected_topics": ["interface_state", "connectivity_testing"],
        "fault_resolution_score": 55,
        "network_health_score": 65,
    },
    {
        "target_topic": "ip_addressing",
        "priority": "medium",
        "scenario_id": "campus-core-routing",
        "difficulty": "easy",
        "failed_check_ids": [
            "campus_check_1_client1_address",
            "campus_check_3_client2_address",
        ],
        "failed_topics": ["ip_addressing"],
        "affected_topics": ["ip_addressing", "connectivity_testing"],
        "fault_resolution_score": 80,
        "network_health_score": 80,
    },
    {
        "target_topic": "connectivity_testing",
        "priority": "high",
        "scenario_id": "campus-core-routing",
        "difficulty": "hard",
        "failed_check_ids": [
            "campus_check_5_client1_to_client2_connectivity",
            "campus_check_6_client2_to_client1_connectivity",
        ],
        "failed_topics": ["connectivity_testing"],
        "affected_topics": ["connectivity_testing", "static_routing"],
        "fault_resolution_score": 63,
        "network_health_score": 63,
    },
]


def get_training_samples() -> list[dict[str, Any]]:
    return deepcopy(AUTONETLAB_ML_TRAINING_SAMPLES)
