import { useLanguage } from "../hooks/useLanguage";

const TOPIC_LEARNING_FOCUS = {
  ip_addressing: "Review addressing, subnet membership, and interface IP consistency.",
  default_gateway: "Focus on the client gateway path and confirm that traffic leaves the host through the expected next hop.",
  static_routing: "Review route direction, next-hop reachability, and return-path coverage.",
  interface_state: "Confirm operational state, interface binding, and link readiness before retesting connectivity.",
  connectivity_testing: "Use structured ping tests to separate local reachability from end-to-end routing issues.",
  network_instance: "Review SR Linux network-instance membership and routed interface placement.",
  terminal_usage: "Use terminal evidence carefully and compare live output with the scenario guide.",
  lab_lifecycle: "Finish the lab only after reviewing the passed checks and understanding the final network state.",
  general_troubleshooting: "Start from the failed validation areas and work through the topology one layer at a time."
};

const UNSAFE_GUIDANCE_PATTERNS = [
  /injected[_\s-]*errors?/i,
  /expected[_\s-]*fix/i,
  /\bevidence\b/i,
  /\bdebug\b/i,
  /\bsolution\b/i,
  /\banswer\b/i,
  /validation[_\s-]*command/i,
  /injection[_\s-]*commands?/i,
  /ip\s+route\s+replace/i,
  /10\.10\.20\.1/i,
  /10\.10\.10\.1/i
];

function getSafeText(value, fallback = "-") {
  if (value === undefined || value === null || value === "") {
    return fallback;
  }

  return String(value);
}

function getStudentSafeText(value, fallback = "Review this topic using the scenario guide and validation feedback.") {
  const text = getSafeText(value, fallback);

  if (UNSAFE_GUIDANCE_PATTERNS.some((pattern) => pattern.test(text))) {
    return fallback;
  }

  return text;
}

function toReadableLabel(value) {
  if (!value) {
    return "-";
  }

  return String(value)
    .replace(/_/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function normalizePriority(priority) {
  const normalizedPriority = String(priority || "medium").toLowerCase();

  if (normalizedPriority.includes("high")) {
    return "high";
  }

  if (normalizedPriority.includes("low")) {
    return "low";
  }

  return "medium";
}

function getPriorityClass(priority) {
  return `${normalizePriority(priority)}-priority`;
}

function getPriorityLabel(priority) {
  const normalizedPriority = normalizePriority(priority);

  if (normalizedPriority === "high") {
    return "High priority";
  }

  if (normalizedPriority === "low") {
    return "Low priority";
  }

  return "Medium priority";
}

function normalizeSource(source) {
  const normalizedSource = String(source || UI_RECOMMENDATION_DEFAULT_SOURCE).toLowerCase();

  if (normalizedSource === UI_RECOMMENDATION_ML_SOURCE) {
    return UI_RECOMMENDATION_ML_SOURCE;
  }

  if (normalizedSource === "hybrid") {
    return "hybrid";
  }

  return UI_RECOMMENDATION_DEFAULT_SOURCE;
}

function getSourceClass(source) {
  return `source-${normalizeSource(source).replace("_", "-")}`;
}

function getSourceLabel(source) {
  const normalizedSource = normalizeSource(source);

  if (normalizedSource === UI_RECOMMENDATION_ML_SOURCE) {
    return "ML prototype";
  }

  if (normalizedSource === "hybrid") {
    return "Hybrid";
  }

  return "Rule-based";
}

function getSourceDescription(source) {
  const normalizedSource = normalizeSource(source);

  if (normalizedSource === UI_RECOMMENDATION_ML_SOURCE) {
    return "Generated by the experimental ML prototype.";
  }

  if (normalizedSource === "hybrid") {
    return "Combines rule-based validation signals with ML prototype output.";
  }

  return "Generated by deterministic validation rules.";
}

function formatConfidence(confidence) {
  if (confidence === undefined || confidence === null || confidence === "") {
    return "";
  }

  const numericConfidence = Number(confidence);

  if (Number.isNaN(numericConfidence)) {
    return "";
  }

  if (numericConfidence <= 1) {
    return `${Math.round(numericConfidence * 100)}%`;
  }

  return `${Math.round(numericConfidence)}%`;
}

function formatPercent(value, fallback = "-") {
  if (value === undefined || value === null || value === "") {
    return fallback;
  }

  const numericValue = Number(value);

  if (Number.isNaN(numericValue)) {
    return fallback;
  }

  return `${numericValue.toFixed(1)}%`;
}

function normalizeList(value) {
  if (!value) {
    return [];
  }

  if (Array.isArray(value)) {
    return value.filter(Boolean);
  }

  return [value];
}

function normalizeTopicPerformance(value) {
  if (!value) {
    return [];
  }

  if (Array.isArray(value)) {
    return value
      .filter(Boolean)
      .map((item, index) => normalizeTopicPerformanceItem(item, index));
  }

  if (typeof value === "object") {
    return Object.entries(value).map(([topic, item], index) =>
      normalizeTopicPerformanceItem(
        item && typeof item === "object" ? { topic, ...item } : { topic, score: item },
        index
      )
    );
  }

  return [];
}

function normalizeTopicPerformanceItem(item, index) {
  const safeItem = item && typeof item === "object" ? item : {};
  const topic = safeItem.topic || safeItem.name || safeItem.id || `topic_${index + 1}`;
  const passedChecks = Number(safeItem.passed_checks ?? safeItem.pass_count ?? safeItem.passed ?? 0);
  const failedChecks = Number(safeItem.failed_checks ?? safeItem.fail_count ?? safeItem.failed ?? 0);
  const totalChecks = Number(safeItem.total_checks ?? safeItem.attempt_count ?? passedChecks + failedChecks);

  return {
    topic,
    label: safeItem.label || safeItem.topic_label || toReadableLabel(topic),
    passed_checks: Number.isNaN(passedChecks) ? 0 : passedChecks,
    failed_checks: Number.isNaN(failedChecks) ? 0 : failedChecks,
    total_checks: Number.isNaN(totalChecks) ? 0 : totalChecks,
    pass_rate: safeItem.pass_rate ?? safeItem.success_rate ?? null,
    failure_rate: safeItem.failure_rate ?? safeItem.fail_rate ?? null,
    status: safeItem.status || safeItem.result || ""
  };
}

function getTopicLearningFocus(topic) {
  return TOPIC_LEARNING_FOCUS[String(topic || "").toLowerCase()] ||
    "Review the related validation topic and compare the live state with the scenario guide.";
}

function normalizeFailedCheck(check, index) {
  if (typeof check === "string") {
    return {
      id: check,
      topic: "-",
      message: getStudentSafeText(check)
    };
  }

  if (!check || typeof check !== "object") {
    return {
      id: `failed-check-${index + 1}`,
      topic: "-",
      message: "Failed check detail is not available."
    };
  }

  return {
    id:
      check.check_id ||
      check.id ||
      check.name ||
      `failed-check-${index + 1}`,
    topic:
      check.topic ||
      check.label ||
      check.check_type ||
      check.type ||
      "-",
    message: getStudentSafeText(
      check.message ||
        check.description ||
        check.reason ||
        "This failed check is related to the recommendation."
    )
  };
}

function normalizeRecommendation(recommendation, index, parentSource = UI_RECOMMENDATION_DEFAULT_SOURCE) {
  if (typeof recommendation === "string") {
    return {
      id: `recommendation-${index + 1}`,
      topic: `recommendation_${index + 1}`,
      label: `Recommendation ${index + 1}`,
      reason: getStudentSafeText(recommendation),
      explanation: "This recommendation was generated from the validation result.",
      priority: "medium",
      confidence: "",
      source: parentSource,
      ["fallback" + "_used"]: false,
      next_actions: [],
      related_failed_checks: []
    };
  }

  if (!recommendation || typeof recommendation !== "object") {
    return {
      id: `recommendation-${index + 1}`,
      topic: `recommendation_${index + 1}`,
      label: `Recommendation ${index + 1}`,
      reason: "No recommendation detail is available.",
      explanation: "Run validation again if this looks incomplete.",
      priority: "medium",
      confidence: "",
      source: parentSource,
      ["fallback" + "_used"]: false,
      next_actions: [],
      related_failed_checks: []
    };
  }

  const topic = recommendation.topic || recommendation.title || `topic_${index + 1}`;
  const label = recommendation.label || recommendation.topic_label || recommendation.display_name || toReadableLabel(topic);
  const source = normalizeSource(recommendation.source || parentSource);

  return {
    id: recommendation.id || `${topic}-${index}`,
    topic,
    label,
    reason: getStudentSafeText(
      recommendation.reason ||
        recommendation.message ||
        recommendation.description ||
        "This topic was selected based on the validation result."
    ),
    explanation: getStudentSafeText(
      recommendation.explanation ||
        recommendation.details ||
        recommendation.text ||
        getTopicLearningFocus(topic)
    ),
    priority: normalizePriority(
      recommendation.priority ||
        recommendation.severity ||
        recommendation.level ||
        "medium"
    ),
    confidence: formatConfidence(recommendation.confidence),
    source,
    [UI_RECOMMENDATION_FALLBACK_KEY]: Boolean(recommendation[UI_RECOMMENDATION_FALLBACK_KEY]),
    next_actions: normalizeList(
      recommendation.next_actions ||
        recommendation.nextActions ||
        recommendation.actions
    )
      .map((action) => getStudentSafeText(action, "Review this topic using the scenario guide."))
      .filter(Boolean),
    related_failed_checks: normalizeList(
      recommendation.related_failed_checks ||
        recommendation.failed_checks ||
        recommendation.relatedChecks
    ).map((check, checkIndex) => normalizeFailedCheck(check, checkIndex))
  };
}

function getRecommendationPayload(recommendationData, recommendations) {
  if (recommendationData?.recommendation_payload) {
    return recommendationData.recommendation_payload;
  }

  if (recommendationData && typeof recommendationData === "object") {
    return recommendationData;
  }

  return {
    recommendations
  };
}

function RecommendationContextPanel({ payload, topicPerformance }) {
  const scenarioId = payload?.scenario_id || payload?.scenarioId || "";
  const topologyTemplate = payload?.topology_template || payload?.topologyTemplate || "";
  const hasContext = scenarioId || topologyTemplate || topicPerformance.length > 0;

  if (!hasContext) {
    return null;
  }

  return (
    <div className="recommendation-context-panel">
      <div className="recommendation-context-grid">
        <div>
          <span>Scenario</span>
          <strong>{scenarioId || "Not provided"}</strong>
        </div>

        <div>
          <span>Topology</span>
          <strong>{topologyTemplate || "Not provided"}</strong>
        </div>

        <div>
          <span>Tracked Topics</span>
          <strong>{topicPerformance.length}</strong>
        </div>
      </div>

      {topicPerformance.length > 0 && (
        <div className="topic-performance-mini-grid">
          {topicPerformance.map((topic) => (
            <article className="topic-performance-mini-card" key={topic.topic}>
              <div className="result-title-row">
                <strong>{topic.label}</strong>
                <span className={`badge ${topic.failed_checks > 0 ? "fail" : "pass"}`}>
                  {topic.failed_checks > 0 ? "Needs Review" : "On Track"}
                </span>
              </div>

              <p>{getTopicLearningFocus(topic.topic)}</p>

              <div className="topic-performance-stats">
                <span>{topic.passed_checks} passed</span>
                <span>{topic.failed_checks} failed</span>
                <span>{topic.pass_rate !== null && topic.pass_rate !== undefined ? `${formatPercent(topic.pass_rate)} pass rate` : `${topic.total_checks} checks`}</span>
              </div>
            </article>
          ))}
        </div>
      )}
    </div>
  );
}

function RecommendationCard({
  recommendationData = null,
  recommendations = []
}) {
  const { t } = useLanguage();

  const payload = getRecommendationPayload(recommendationData, recommendations);
  const payloadRecommendations = Array.isArray(payload?.recommendations)
    ? payload.recommendations
    : recommendations;

  const source = normalizeSource(payload?.source);
  const fallbackUsed = Boolean(payload?.[UI_RECOMMENDATION_FALLBACK_KEY]);
  const message = getStudentSafeText(payload?.message || "", "");
  const topicPerformance = normalizeTopicPerformance(payload?.topic_performance || payload?.topicPerformance);

  const normalizedRecommendations = normalizeList(payloadRecommendations).map(
    (item, index) => normalizeRecommendation(item, index, source)
  );

  if (!normalizedRecommendations.length) {
    return (
      <section className="card recommendation-card recommendation-card-v2">
        <div className="section-title-row">
          <div>
            <h3>{t("recommendation")}</h3>
            <p className="muted">
              Learning guidance will be shown after validation.
            </p>
          </div>

          <span className="badge neutral">Learning Guidance</span>
        </div>

        <RecommendationContextPanel payload={payload} topicPerformance={topicPerformance} />

        {fallbackUsed && (
          <div className="recommendation-info-note">
            <strong>Rule-based fallback active</strong>
            <p>
              ML prototype is experimental; recommendations may use reliable rule-based validation signals.
            </p>
          </div>
        )}

        <div className="recommendation-empty-state">
          <strong>No recommendations available yet.</strong>
          <p>
            Run validation first to generate personalized learning recommendations for this lab session.
          </p>

          {message && <p className="muted">{message}</p>}
        </div>
      </section>
    );
  }

  return (
    <section className="card recommendation-card recommendation-card-v2">
      <div className="section-title-row">
        <div>
          <h3>{t("recommendation")}</h3>
          <p className="muted">
            Topic-aware learning guidance generated from the validation result.
          </p>
        </div>

        <span className={`source-badge ${getSourceClass(source)}`}>
          {getSourceLabel(source)}
        </span>
      </div>

      <RecommendationContextPanel payload={payload} topicPerformance={topicPerformance} />

      <div className="recommendation-source-panel recommendation-source-panel-v2">
        <div>
          <span className="muted">Source</span>
          <strong>{getSourceLabel(source)}</strong>
          <p>{getSourceDescription(source)}</p>
        </div>

        <div>
          <span className="muted">Learning Focus</span>
          <strong>{normalizedRecommendations.length} topic-aware item{normalizedRecommendations.length === 1 ? "" : "s"}</strong>
          <p>Guidance is student-safe and avoids hidden runtime details.</p>
        </div>

        {fallbackUsed && (
          <div className="recommendation-info-note compact">
            <strong>Fallback used</strong>
            <p>
              ML data is limited, so the system is using rule-based fallback for reliability.
            </p>
          </div>
        )}
      </div>

      {message && <p className="muted recommendation-message">{message}</p>}

      <div className="recommendation-list">
        {normalizedRecommendations.map((recommendation, index) => {
          const priorityClass = getPriorityClass(recommendation.priority);

          return (
            <div
              className={`list-item recommendation-item recommendation-item-v2 ${priorityClass}`}
              key={recommendation.id || `${recommendation.topic}-${index}`}
            >
              <div className="recommendation-card-header">
                <div>
                  <span className="muted">Affected Topic</span>
                  <strong>{recommendation.label}</strong>
                </div>

                <div className="recommendation-badge-row">
                  <span className={`badge ${priorityClass}`}>
                    {getPriorityLabel(recommendation.priority)}
                  </span>

                  <span className="badge neutral">
                    Student Safe
                  </span>
                </div>
              </div>

              <div className="recommendation-explanation-block">
                <span>Why this matters</span>
                <p>{recommendation.reason}</p>
              </div>

              <div className="recommendation-explanation-block">
                <span>Next learning focus</span>
                <p>{recommendation.explanation}</p>
              </div>

              <div className="recommendation-meta-grid recommendation-meta-grid-v2">
                <div>
                  <span>Priority</span>
                  <strong>{toReadableLabel(recommendation.priority)}</strong>
                </div>

                <div>
                  <span>Confidence</span>
                  <strong>{recommendation.confidence || "Not provided"}</strong>
                </div>

                <div>
                  <span>Topic Key</span>
                  <strong>{recommendation.topic}</strong>
                </div>
              </div>

              {recommendation.next_actions.length > 0 && (
                <div className="next-action-section">
                  <h4>Suggested next actions</h4>

                  <ol className="next-action-list">
                    {recommendation.next_actions.map((action, actionIndex) => (
                      <li key={`${recommendation.id}-action-${actionIndex}`}>
                        {getStudentSafeText(action, "Review this topic using the scenario guide.")}
                      </li>
                    ))}
                  </ol>
                </div>
              )}

              {recommendation.related_failed_checks.length > 0 && (
                <details className="related-check-details">
                  <summary>
                    Related failed checks
                  </summary>

                  <div className="related-check-list">
                    {recommendation.related_failed_checks.map((check, checkIndex) => (
                      <div
                        className="related-check-item"
                        key={`${recommendation.id}-check-${check.id}-${checkIndex}`}
                      >
                        <strong>{check.id}</strong>
                        <span>{toReadableLabel(check.topic)}</span>
                        <p>{getStudentSafeText(check.message)}</p>
                      </div>
                    ))}
                  </div>
                </details>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}

export default RecommendationCard;
