import { useLanguage } from "../hooks/useLanguage";

function getSafeText(value, fallback = "-") {
  if (value === undefined || value === null || value === "") {
    return fallback;
  }

  return String(value);
}

function toReadableLabel(value) {
  if (!value) {
    return "-";
  }

  return String(value)
    .replace(/_/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function normalizePriority(priority) {
  const normalizedPriority = String(priority || "medium").toLowerCase();

  if (normalizedPriority.includes("high")) {
    return "high";
  }

  if (normalizedPriority.includes("low")) {
    return "low";
  }

  return "medium";
}

function getPriorityClass(priority) {
  return `${normalizePriority(priority)}-priority`;
}

function getPriorityLabel(priority) {
  const normalizedPriority = normalizePriority(priority);

  if (normalizedPriority === "high") {
    return "High priority";
  }

  if (normalizedPriority === "low") {
    return "Low priority";
  }

  return "Medium priority";
}

function normalizeSource(source) {
  const normalizedSource = String(source || "rule_based").toLowerCase();

  if (normalizedSource === "ml_prototype") {
    return "ml_prototype";
  }

  if (normalizedSource === "hybrid") {
    return "hybrid";
  }

  return "rule_based";
}

function getSourceClass(source) {
  return `source-${normalizeSource(source).replace("_", "-")}`;
}

function getSourceLabel(source) {
  const normalizedSource = normalizeSource(source);

  if (normalizedSource === "ml_prototype") {
    return "ML prototype";
  }

  if (normalizedSource === "hybrid") {
    return "Hybrid";
  }

  return "Rule-based";
}

function getSourceDescription(source) {
  const normalizedSource = normalizeSource(source);

  if (normalizedSource === "ml_prototype") {
    return "Generated by the experimental ML prototype.";
  }

  if (normalizedSource === "hybrid") {
    return "Combines rule-based validation signals with ML prototype output.";
  }

  return "Generated by deterministic validation rules.";
}

function formatConfidence(confidence) {
  if (confidence === undefined || confidence === null || confidence === "") {
    return "";
  }

  const numericConfidence = Number(confidence);

  if (Number.isNaN(numericConfidence)) {
    return "";
  }

  if (numericConfidence <= 1) {
    return `${Math.round(numericConfidence * 100)}%`;
  }

  return `${Math.round(numericConfidence)}%`;
}

function normalizeList(value) {
  if (!value) {
    return [];
  }

  if (Array.isArray(value)) {
    return value.filter(Boolean);
  }

  return [value];
}

function normalizeFailedCheck(check, index) {
  if (typeof check === "string") {
    return {
      id: check,
      topic: "-",
      message: check
    };
  }

  if (!check || typeof check !== "object") {
    return {
      id: `failed-check-${index + 1}`,
      topic: "-",
      message: "Failed check detail is not available."
    };
  }

  return {
    id:
      check.check_id ||
      check.id ||
      check.name ||
      `failed-check-${index + 1}`,
    topic:
      check.topic ||
      check.label ||
      check.check_type ||
      check.type ||
      "-",
    message:
      check.message ||
      check.description ||
      check.reason ||
      "This failed check is related to the recommendation."
  };
}

function normalizeRecommendation(recommendation, index, parentSource = "rule_based") {
  if (typeof recommendation === "string") {
    return {
      id: `recommendation-${index + 1}`,
      topic: `Recommendation ${index + 1}`,
      label: `Recommendation ${index + 1}`,
      reason: recommendation,
      explanation: "This recommendation was generated from the validation result.",
      priority: "medium",
      confidence: "",
      source: parentSource,
      fallback_used: false,
      next_actions: [],
      related_failed_checks: []
    };
  }

  if (!recommendation || typeof recommendation !== "object") {
    return {
      id: `recommendation-${index + 1}`,
      topic: `Recommendation ${index + 1}`,
      label: `Recommendation ${index + 1}`,
      reason: "No recommendation detail is available.",
      explanation: "Run validation again if this looks incomplete.",
      priority: "medium",
      confidence: "",
      source: parentSource,
      fallback_used: false,
      next_actions: [],
      related_failed_checks: []
    };
  }

  const topic = recommendation.topic || recommendation.title || `topic-${index + 1}`;
  const label = recommendation.label || recommendation.topic_label || recommendation.display_name || toReadableLabel(topic);
  const source = normalizeSource(recommendation.source || parentSource);

  return {
    id: recommendation.id || `${topic}-${index}`,
    topic,
    label,
    reason:
      recommendation.reason ||
      recommendation.message ||
      recommendation.description ||
      "This topic was selected based on the validation result.",
    explanation:
      recommendation.explanation ||
      recommendation.details ||
      recommendation.text ||
      "Review this topic before attempting a harder lab.",
    priority: normalizePriority(
      recommendation.priority ||
        recommendation.severity ||
        recommendation.level ||
        "medium"
    ),
    confidence: formatConfidence(recommendation.confidence),
    source,
    fallback_used: Boolean(recommendation.fallback_used),
    next_actions: normalizeList(
      recommendation.next_actions ||
        recommendation.nextActions ||
        recommendation.actions
    ),
    related_failed_checks: normalizeList(
      recommendation.related_failed_checks ||
        recommendation.failed_checks ||
        recommendation.relatedChecks
    ).map((check, checkIndex) => normalizeFailedCheck(check, checkIndex))
  };
}

function getRecommendationPayload(recommendationData, recommendations) {
  if (recommendationData?.recommendation_payload) {
    return recommendationData.recommendation_payload;
  }

  if (recommendationData && typeof recommendationData === "object") {
    return recommendationData;
  }

  return {
    recommendations
  };
}

function RecommendationCard({
  recommendationData = null,
  recommendations = []
}) {
  const { t } = useLanguage();

  const payload = getRecommendationPayload(recommendationData, recommendations);
  const payloadRecommendations = Array.isArray(payload?.recommendations)
    ? payload.recommendations
    : recommendations;

  const source = normalizeSource(payload?.source);
  const fallbackUsed = Boolean(payload?.fallback_used);
  const message = payload?.message || "";

  const normalizedRecommendations = normalizeList(payloadRecommendations).map(
    (item, index) => normalizeRecommendation(item, index, source)
  );

  if (!normalizedRecommendations.length) {
    return (
      <section className="card recommendation-card">
        <div className="section-title-row">
          <div>
            <h3>{t("recommendation")}</h3>
            <p className="muted">
              Learning guidance will be shown after validation.
            </p>
          </div>

          <span className={`source-badge ${getSourceClass(source)}`}>
            {getSourceLabel(source)}
          </span>
        </div>

        {fallbackUsed && (
          <div className="recommendation-info-note">
            <strong>Rule-based fallback active</strong>
            <p>
              ML prototype is experimental; recommendations may use reliable rule-based validation signals.
            </p>
          </div>
        )}

        <div className="recommendation-empty-state">
          <strong>No recommendations available yet.</strong>
          <p>
            Run validation first to generate personalized learning recommendations for this lab session.
          </p>

          {message && <p className="muted">{message}</p>}
        </div>
      </section>
    );
  }

  return (
    <section className="card recommendation-card">
      <div className="section-title-row">
        <div>
          <h3>{t("recommendation")}</h3>
          <p className="muted">
            Explanation-based recommendations generated from the validation result.
          </p>
        </div>

        <span className={`source-badge ${getSourceClass(source)}`}>
          {getSourceLabel(source)}
        </span>
      </div>

      <div className="recommendation-source-panel">
        <div>
          <span className="muted">Source</span>
          <strong>{getSourceLabel(source)}</strong>
          <p>{getSourceDescription(source)}</p>
        </div>

        {fallbackUsed && (
          <div className="recommendation-info-note compact">
            <strong>Fallback used</strong>
            <p>
              ML data is limited, so the system is using rule-based fallback for reliability.
            </p>
          </div>
        )}
      </div>

      {message && <p className="muted recommendation-message">{message}</p>}

      <div className="recommendation-list">
        {normalizedRecommendations.map((recommendation, index) => {
          const priorityClass = getPriorityClass(recommendation.priority);

          return (
            <div
              className={`list-item recommendation-item ${priorityClass}`}
              key={recommendation.id || `${recommendation.topic}-${index}`}
            >
              <div className="recommendation-card-header">
                <div>
                  <span className="muted">Topic</span>
                  <strong>{recommendation.label}</strong>
                </div>

                <div className="recommendation-badge-row">
                  <span className={`badge ${priorityClass}`}>
                    {getPriorityLabel(recommendation.priority)}
                  </span>

                  <span className={`source-badge ${getSourceClass(recommendation.source)}`}>
                    {getSourceLabel(recommendation.source)}
                  </span>
                </div>
              </div>

              <div className="recommendation-explanation-block">
                <span>Reason</span>
                <p>{recommendation.reason}</p>
              </div>

              <div className="recommendation-explanation-block">
                <span>Explanation</span>
                <p>{recommendation.explanation}</p>
              </div>

              <div className="recommendation-meta-grid">
                <div>
                  <span>Priority</span>
                  <strong>{toReadableLabel(recommendation.priority)}</strong>
                </div>

                <div>
                  <span>Confidence</span>
                  <strong>{recommendation.confidence || "Not provided"}</strong>
                </div>
              </div>

              {recommendation.next_actions.length > 0 && (
                <div className="next-action-section">
                  <h4>Suggested next actions</h4>

                  <ol className="next-action-list">
                    {recommendation.next_actions.map((action, actionIndex) => (
                      <li key={`${recommendation.id}-action-${actionIndex}`}>
                        {getSafeText(action, "Review this topic.")}
                      </li>
                    ))}
                  </ol>
                </div>
              )}

              {recommendation.related_failed_checks.length > 0 && (
                <details className="related-check-details">
                  <summary>
                    Related failed checks
                  </summary>

                  <div className="related-check-list">
                    {recommendation.related_failed_checks.map((check, checkIndex) => (
                      <div
                        className="related-check-item"
                        key={`${recommendation.id}-check-${check.id}-${checkIndex}`}
                      >
                        <strong>{check.id}</strong>
                        <span>{toReadableLabel(check.topic)}</span>
                        <p>{check.message}</p>
                      </div>
                    ))}
                  </div>
                </details>
              )}
            </div>
          );
        })}
      </div>
    </section>
  );
}

export default RecommendationCard;
